- name: "Install logstash dependencies"
  yum: >
    name={{ item }}
    state=present
    enablerepo=epel
  with_items:
    - java-1.7.0-openjdk
  tags:
    - logstash
    - pkgs

- name: "Download Logstash"
  get_url: >
    url={{ item.link }}
    dest={{ item.dest }}
  with_items:
    - { link: 'http://download.elastic.co/logstash/logstash/packages/centos/logstash-{{ logstash_version }}-1.noarch.rpm', dest: '/tmp/logstash-{{ logstash_version }}-1.noarch.rpm' }
    - { link: 'http://download.elastic.co/logstash/logstash/packages/centos/logstash-{{ logstash_version }}-1.noarch.rpm.sha1.txt', dest: '/tmp/logstash-{{ logstash_version }}-1.noarch.rpm.sha1.txt' }
  tags:
    - logstash
    - pkgs

- name: "Verify Logstash checksum"
  shell: |
    executable=/bin/bash
    chdir=/tmp

    # Ansible get_url only supports sha256.
    # Elastic provides only a sha1 checksum.
    # Issue for sha1 support: https://github.com/ansible/ansible/issues/10216
    sha1_binary="$(sha1sum logstash-{{ logstash_version }}-1.noarch.rpm | cut -d' ' -f1 | cut -f1)"
    sha1_file="$(cat logstash-{{ logstash_version }}-1.noarch.rpm.sha1.txt | cut -d' ' -f1 | cut -f1)"

    if
        [ "$sha1_binary" == "$sha1_file" ]
    then
       echo "SHA1 checksum succeeded."
    else
       echo "SHA1 checksum failed."
       exit 1
    fi
  tags:
    - logstash
    - pkgs

- name: "Install logstash"
  yum: >
    name=/tmp/logstash-{{ logstash_version }}-1.noarch.rpm
    state=present
  tags:
    - logstash
    - pkgs

- name: "Install /etc/logstash/conf.d/logstash.conf"
  template: >
    src=logstash.conf.j2
    dest=/etc/logstash/conf.d/logstash.conf
    owner=logstash
    group=logstash
    mode=0600
  tags:
    - logstash
    - files
    - configs
  notify:
    - Restart logstash

- name: "Set Logstash to run as root to be able to listen on port 514"
  lineinfile: >
    dest=/etc/sysconfig/logstash
    state=present
    regexp="LS_USER"
    line="LS_USER=root"
  tags:
    - logstash
    - files

- name: "Make sure logstash is running"
  service: >
    name=logstash
    state=running
    enabled=yes
    runlevel=5
  tags:
    - logstash
    - service
