- name: "Install logstash dependencies"
  apt: >
    name={{ item }}
    update_cache=yes
    state=present
  with_items:
    - openjdk-7-jre-headless
    - logrotate
  when: ansible_distribution_release == "wheezy"
  tags:
    - logstash
    - pkgs

- name: "Install logstash dependencies"
  apt: >
    name={{ item }}
    update_cache=yes
    state=present
    default_release={{ ansible_distribution_release }}-backports
  with_items:
    - openjdk-8-jre-headless
    - logrotate
  when: ansible_distribution_release == "jessie"
  tags:
    - logstash
    - pkgs

- name: "Ensure correct Java version (1.7)"
  shell:
    update-java-alternatives -s java-1.7.0-openjdk-amd64 --jre-headless
  when: ansible_distribution_release == "wheezy"
  tags:
    - logstash
    - pkgs

- name: "Ensure correct Java version (1.8)"
  shell:
    update-java-alternatives -s java-1.8.0-openjdk-amd64 --jre-headless
  when: ansible_distribution_release == "jessie"
  tags:
    - logstash
    - pkgs

- name: "Download Logstash"
  get_url: >
    url={{ item.link }}
    dest={{ item.dest }}
  with_items:
    - { link: "http://download.elastic.co/logstash/logstash/packages/debian/logstash_{{ logstash_version }}-1_all.deb", dest: "/tmp/logstash_{{ logstash_version }}-1_all.deb" }
    - { link: "http://download.elastic.co/logstash/logstash/packages/debian/logstash_{{ logstash_version }}-1_all.deb.sha1.txt", dest: "/tmp/logstash_{{ logstash_version }}-1_all.deb.sha1.txt" }
  tags:
    - logstash
    - pkgs

- name: "Verify Logstash checksum"
  shell: |
    executable=/bin/bash
    chdir=/tmp

    # Ansible get_url only supports sha256.
    # Elastic provides only a sha1 checksum.
    # Issue for sha1 support: https://github.com/ansible/ansible/issues/10216
    sha1_binary="$(sha1sum logstash_{{ logstash_version }}-1_all.deb | cut -d' ' -f1 | cut -f1)"
    sha1_file="$(cat logstash_{{ logstash_version }}-1_all.deb.sha1.txt | cut -d' ' -f1 | cut -f1)"

    if
        [ "$sha1_binary" == "$sha1_file" ]
    then
       echo "SHA1 checksum succeeded."
    else
       echo "SHA1 checksum failed."
       exit 1
    fi
  tags:
    - logstash
    - pkgs

- name: "Install logstash"
  apt: >
    deb=/tmp/logstash_{{ logstash_version }}-1_all.deb
    state=present
  tags:
    - logstash
    - pkgs

- name: "Install /etc/logstash/conf.d/logstash.conf"
  template: >
    src=logstash.conf.j2
    dest=/etc/logstash/conf.d/logstash.conf
    owner=root
    group=root
    mode=0600
  tags:
    - logstash
    - files
    - configs
  notify:
    - Restart logstash

- name: "Set Logstash to run as root to be able to listen on port 514 (or any port lower than 1024)"
  lineinfile: >
    dest=/etc/default/logstash
    state=present
    regexp="LS_USER"
    line="LS_USER=root"
  when: logstash_syslog_port <= 1024
  tags:
    - logstash
    - files

- name: "Make sure logstash is running"
  service: >
    name=logstash
    pattern=/opt/logstash/vendor/jruby/lib/jruby.jar
    state=running
    enabled=yes
    runlevel=5
  tags:
    - logstash
    - service
