#####################
# CentOS
- include: centos.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - logstash

#####################
# Debian
- include: debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - logstash

- name: "Install Logstash Plugins (logstash <= 2.0.0)"
  shell: |
    executable=/bin/bash
    creates=/opt/logstash/vendor/bundle/jruby/1.9/gems/{{ item.plugin_name }}-{{ item.plugin_version }}
    chdir=/opt/logstash

    sudo bin/plugin install --version {{ item.plugin_version }} {{ item.plugin_name }}
  with_items: logstash_plugins_1
  when: logstash_version | version_compare('2.0.0', '<')
  tags:
    - logstash

- name: "Install Logstash Plugins (logstash between >=2.0.0 < 2.3.0)"
  shell: |
    executable=/bin/bash
    creates=/opt/logstash/vendor/bundle/jruby/1.9/gems/{{ item.plugin_name }}-{{ item.plugin_version }}
    chdir=/opt/logstash

    sudo bin/plugin install --version {{ item.plugin_version }} {{ item.plugin_name }}
  with_items: logstash_plugins_2
  when: logstash_version | version_compare('2.0.0', '>=') and logstash_version | version_compare('2.3.0', '<')
  tags:
    - logstash

- name: "Install Logstash Plugins (logstash between >=2.0.0 < 2.3.0)"
  shell: |
    executable=/bin/bash
    creates=/opt/logstash/vendor/bundle/jruby/1.9/gems/{{ item.plugin_name }}-{{ item.plugin_version }}
    chdir=/opt/logstash

    sudo bin/plugin install --version {{ item.plugin_version }} {{ item.plugin_name }}
  with_items:
    - { plugin_name: "logstash-output-elasticsearch_java", plugin_version: "2.1.1" }
  when: logstash_elasticsearch_cluster is defined and logstash_version | version_compare('2.0.0', '>=') and logstash_version | version_compare('2.3.0', '<')
  tags:
    - logstash

- name: "Install Logstash Plugins (logstash >=2.3.0)"
  shell: |
    executable=/bin/bash
    creates=/opt/logstash/vendor/bundle/jruby/1.9/gems/{{ item.plugin_name }}-{{ item.plugin_version }}
    chdir=/opt/logstash

    sudo LS_HEAP_SIZE=256m bin/logstash-plugin install --version {{ item.plugin_version }} {{ item.plugin_name }}
  with_items: logstash_plugins_2
  when: logstash_version | version_compare('2.3.0', '>=') and item.plugin_name is defined
  tags:
    - logstash

# Apply fix to logstash-output-syslog to allow ssl-tcp without needing to setup a ssl server with a custom key+cert,
# because we just want to be able to send ssl-tcp.
- name: "Apply patch to logstash-output-syslog-2.1.4 plugin to use ssl-tcp (logstash >=2.3.0)"
  get_url: |
    dest=/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-syslog-2.1.4/lib/logstash/outputs/syslog.rb
    url=https://raw.githubusercontent.com/tokyowizard/logstash-output-syslog/send-ssl-tcp/lib/logstash/outputs/syslog.rb
    mode=644
    force=yes
  with_items: logstash_plugins_2
  when: logstash_version | version_compare('2.3.0', '>=') and item.plugin_name == "logstash-output-syslog" and item.plugin_version =="2.1.4"
  tags:
    - logstash

- name: "Install Logstash Plugins (logstash >= 2.3.0)"
  shell: |
    executable=/bin/bash
    creates=/opt/logstash/vendor/bundle/jruby/1.9/gems/{{ item.plugin_name }}-{{ item.plugin_version }}
    chdir=/opt/logstash

    sudo LS_HEAP_SIZE=256m bin/logstash-plugin install --version {{ item.plugin_version }} {{ item.plugin_name }}
  with_items:
    - { plugin_name: "logstash-output-elasticsearch_java", plugin_version: "2.1.3" }
  when: logstash_elasticsearch_cluster is defined and logstash_version | version_compare('2.3.0', '>=')
  tags:
    - logstash

# Add fix for logstash-output-syslog. See:
# https://github.com/logstash-plugins/logstash-output-syslog/commit/f5a4be2a56f184b134c01fb1d0e0c9a09be11aa8#diff-3ccf50b4bfe2babe74a94ff1b3a791a6
- name: "Apply fix for the logstash-output-syslog plugin"
  get_url: >
    url="https://raw.githubusercontent.com/logstash-plugins/logstash-output-syslog/f5a4be2a56f184b134c01fb1d0e0c9a09be11aa8/lib/logstash/outputs/syslog.rb"
    dest="/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-syslog-0.1.4/lib/logstash/outputs/syslog.rb"
    force=yes
  when: logstash_version | version_compare('2.0.0', '<')
  tags:
    - logstash

- name: "Make sure logstash is running"
  service: >
    name=logstash
    state=running
    enabled=yes
    runlevel=5
  tags:
    - logstash
    - service
